
let Vibrant = null;
try {
  const m = require('node-vibrant/node');
  Vibrant = m?.default || m?.Vibrant || m;
} catch (e) {
  try {
    const m2 = require('node-vibrant');
    Vibrant = m2?.default || m2?.Vibrant || m2;
  } catch (e2) {
    console.error('node-vibrant not found. Please install it with `npm install node-vibrant`');
    process.exit(1);
  }
}
const path = require('path');
const fs = require('fs');

const imageArg = process.argv[2] || 'public/imagenes/logo.png';
const imagePath = path.resolve(process.cwd(), imageArg);
const outCss = path.resolve(process.cwd(), 'src/app/theme-colors.css');
const outAppCss = path.resolve(process.cwd(), 'src/app/app.css');

function darkenHex(hex, percent) {
  const bigint = parseInt(hex.replace('#', ''), 16);
  let r = (bigint >> 16) & 255;
  let g = (bigint >> 8) & 255;
  let b = bigint & 255;
  r = Math.max(0, Math.min(255, Math.round(r * (1 - percent/100))));
  g = Math.max(0, Math.min(255, Math.round(g * (1 - percent/100))));
  b = Math.max(0, Math.min(255, Math.round(b * (1 - percent/100))));
  return '#' + ((1 << 24) + (r << 16) + (g << 8) + b).toString(16).slice(1).toUpperCase();
}

async function run(){
  if(!fs.existsSync(imagePath)){
    console.error('Image not found:', imagePath);
    process.exit(1);
  }
  try{
    let palette;
    if(typeof Vibrant.from === 'function'){
      palette = await Vibrant.from(imagePath).getPalette();
    }else{
      // older/newer API fallback
      const v = new Vibrant(imagePath);
      palette = await v.getPalette();
    }
    const pick = (name) => {
      const sw = palette[name];
      if(!sw) return null;
      if(typeof sw.hex === 'function') return sw.hex().toUpperCase();
      if(typeof sw.getHex === 'function') return sw.getHex().toUpperCase();
      if(sw._rgb) {
        const rgb = sw._rgb.map(v => Math.max(0, Math.min(255, Math.round(v))));
        return '#' + rgb.map(v => v.toString(16).padStart(2, '0')).join('').toUpperCase();
      }
      return null;
    }; 
    const rgbFromSwatch = (sw) => sw && sw._rgb ? sw._rgb.map(v => Math.round(v)) : null;
    const isBlueRgb = (rgb) => {
      if(!rgb) return false;
      const [r,g,b] = rgb;
      return b > r && b > g && b > 100;
    };
    const isYellowRgb = (rgb) => {
      if(!rgb) return false;
      const [r,g,b] = rgb;
      return r > 200 && g > 120 && b < 200;
    };

    let primary = null;
    const pCandidates = ['DarkVibrant','DarkMuted','Vibrant','Muted','LightVibrant','LightMuted'];
    for(const key of pCandidates){
      const sw = palette[key];
      if(sw && isBlueRgb(rgbFromSwatch(sw))){ primary = pick(key); break; }
    }
    if(!primary){
      for(const key of pCandidates){ const sw = palette[key]; if(sw){ primary = pick(key); break; } }
    }

    let accent = null;
    const aCandidates = ['LightVibrant','Vibrant','LightMuted','Muted','DarkVibrant'];
    for(const key of aCandidates){ const sw = palette[key]; if(sw && isYellowRgb(rgbFromSwatch(sw))){ accent = pick(key); break; } }
    if(!accent){ for(const key of aCandidates){ const sw = palette[key]; if(sw){ accent = pick(key); break; } } }

    const secondary = pick('Muted') || pick('DarkMuted') || pick('Vibrant') || primary;
    const accentDark = darkenHex(accent, 14);

    const cssContent = `:root {
  --bg-primary: ${primary};
  --bg-secondary: ${secondary};
  --bg-accent: ${accent};
  --bg-accent-dark: ${accentDark};
}
/* Generated by tools/extract-colors.js from ${path.basename(imagePath)} */
`;
    fs.writeFileSync(outCss, cssContent, { encoding: 'utf8' });
    console.log('Wrote theme colors to', outCss);

    let appCss = fs.readFileSync(outAppCss, 'utf8');
    const importLine = "@import './theme-colors.css';";
    if(!appCss.includes(importLine)){
      appCss = importLine + '\n' + appCss;
      fs.writeFileSync(outAppCss, appCss, 'utf8');
      console.log('Inserted import into src/app/app.css');
    } else {
      console.log('Import already present in src/app/app.css');
    }

    console.log('Colors extracted:', primary, secondary, accent, accentDark);
  }catch(err){
    console.error(err);
    process.exit(1);
  }
}

run();
